[program:sim-pendidikan-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/sim-pendidikan/Backend/artisan queue:work database --sleep=3 --tries=3 --timeout=60 --max-time=3600
directory=/var/www/sim-pendidikan/Backend
user=www-data
numprocs=1
autostart=true
autorestart=true
startsecs=3
stopwaitsecs=3600
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/www/sim-pendidikan/Backend/storage/logs/queue-worker.log
